Improvement: Implemented Feedback from Code Review
Tarekkk1/Robusta_FacebookConversions pull request #2
Opened 2023-09-04 18:12 UTC by Tarekkk1

2023-09-05 13:40 UTC, MostafaShehab requested changes

2023-09-05 13:40 UTC, MostafaShehab commented on Observer/PurchaseObserver.php
> +                'id' => (string)$item->getProductId(),
Are you sure that Facebook will accept multiple products in this format? Did you validate this with their docs?

2023-09-05 13:40 UTC, MostafaShehab commented on Plugin/AddToCartGraphQlPlugin.php
> +                if ($cart->getCustomer() && $cart->getCustomer()->getEmail()) {
No need to fetch the customer, simply fetch the `customerEmail` directly from the cart. Note that is might be null if this is a guest cart and the user never reached the checkout cycle.

2023-09-05 13:40 UTC, MostafaShehab commented on Plugin/AddToCartGraphQlPlugin.php
> +                    'event_source_url' => (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
Can you explain what this means?

2023-09-06 03:50 UTC, Tarekkk1 commented on Plugin/AddToCartGraphQlPlugin.php
> +                        'content_id' => $cartItem->getProductId(),
Done

2023-09-06 03:50 UTC, Tarekkk1 commented on Plugin/AddToCartGraphQlPlugin.php
> +                if ($cart->getCustomer() && $cart->getCustomer()->getEmail()) {
Done

2023-09-06 03:52 UTC, Tarekkk1 commented on Plugin/AddToCartGraphQlPlugin.php
> +                    'event_source_url' => (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
This is a good way i have seen it while searching that help people to send the full url to any page any place i have used it just to try it as its my first time to see it

2023-09-06 03:53 UTC, Tarekkk1 commented on Plugin/AddToCartGraphQlPlugin.php
> +                    'event_source_url' => (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
I will remove it or comment it as we dont need it so much

2023-09-06 03:56 UTC, Tarekkk1 commented on Plugin/AddToCartGraphQlPlugin.php
> +                    'event_source_url' => (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
![Screenshot 2023-09-06 065509](https://github.com/Tarekkk1/Robusta_FacebookConversions/assets/112449390/3744f4a1-74e1-448d-9ed9-b262a3fb7854)

2023-09-06 10:20 UTC, MostafaShehab commented on Plugin/AddToCartGraphQlPlugin.php
> +                    'event_source_url' => (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
There is a couple of challenges here. First thing, this is not the standard way in Magento (even though it is the standard in PHP itself). Look into a class called `Request` which comes with Magento, it should have the needed functionality. Second issue, what about mobile applications? They have no url so how will you handle that?

2023-09-06 10:25 UTC, Tarekkk1 commented on Plugin/AddToCartGraphQlPlugin.php
> +                    'event_source_url' => (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
Okaaaaayyy got it, I will read about this feature and I have commented it in last modification

2023-09-06 10:53 UTC, MostafaShehab requested changes

2023-09-06 10:53 UTC, MostafaShehab commented on Observer/PurchaseObserver.php
> +                'id' => (string)$item->getSku(),
Skus are saved as strings, no need to type cast.

2023-09-06 10:53 UTC, MostafaShehab commented on Plugin/AddToCartGraphQlPlugin.php
> +                $customerEmail = '';
This line has no meaning so remove it.

2023-09-06 10:53 UTC, MostafaShehab commented on Plugin/AddToCartGraphQlPlugin.php
> +                    // 'event_source_url' => (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]",
Unless you are leaving this commented line for a reason, it is better to fully remove commented code. Git will track the history for you :D

2023-09-07 10:10 UTC, MostafaShehab approved these changes

2023-09-07 10:11 UTC, merged